baseURL = "https://www.kammerkoret-aurum.no"
theme = "aurum"

ignoreLogs =["warning-goldmark-raw-html"]

pluralizelisttitles = false
summaryLength = 10 
buildFuture = true
enableRobotsTXT = true

defaultContentLanguage = "no"
languageCode = "no-nb"
[languages]
  [languages.no]
    title = "Kammerkoret Aurum"
    languageName = "Norsk"
    weight = 1
  [languages.en]
    title = "Kammerkoret Aurum"
    languageName = "English"
    weight = 2

    



