[no]
title = "Kontakt"
body = "Kammerkoret Aurum tar på seg ulike musikalske oppdrag og har opptak av nye korister hvert halvår. Send oss en mail om du har henvendelser eller spørsmål.\n\n* Epost: [post@kammerkoret-aurum.no](<>)\n* Orgnr: 992 414 162\n* Bankkonto: 1503.34.57976\n* Vipps: #20578\n* Grasrotandel: Kammerkoret Aurum"

[en]
title = "Contact"
body = "Kammerkoret Aurum frequently sings at events for organizations, companies and at private parties. We admit new chorists twice a year. Send an email to [post@kammerkoret-aurum.no](<>) should you have questions or inquiries."
