backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "booking"
    label: "Booking"
    folder: "content/booking"
    create: false
    fields:
      - {label: "Tekst", name: "body", widget: "markdown"}



