backend:
  name: git-gateway
  branch: main


i18n:
  structure: multiple_folders
  locales: [no, en]
  default_locale: no

media_folder: "static/images"
public_folder: "/images"

slug:
  encoding: "ascii"
  clean_accents: true


collections:
  - name: "sider"
    editor:
      preview: false
    label: "Sider"
    files:
      - name: "medlemmer"
        label: "Medlemmer"
        file: "data/medlemmer.yml"
        fields:
          - {label: "Sopran", name: "sopran", widget: "text"}
          - {label: "Alt", name: "alt", widget: "text"}
          - {label: "Tenor", name: "tenor", widget: "text"}
          - {label: "Bass", name: "bass", widget: "text"}
      - name: "utmerkelser"
        label: "Utmerkelser"
        file: "data/no/utmerkelser.yml"
        fields:
          - {label: "Sammendrag", name: "sammendrag", widget: "markdown"}
          - {label: "Utmerkelser", name: "test", widget: "markdown"}
      - name: "utmerkelser-en"
        label: "Utmerkelser (en)"
        file: "data/en/utmerkelser.yml"
        fields:
          - {label: "Sammendrag", name: "sammendrag", widget: "markdown"}
          - {label: "Utmerkelser", name: "test", widget: "markdown"}
      - name: "booking"
        label: "Booking"
        file: "content/booking/index.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "booking_en"
        label: "Booking (en)"
        file: "content/booking/index.en.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "kontakt"
        label: "Kontakt"
        file: "content/kontakt/index.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "kontakt_en"
        label: "Kontakt (en)"
        file: "content/kontakt/index.en.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "opptak"
        label: "Opptak"
        file: "content/opptak/index.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "opptak_en"
        label: "Opptak (en)"
        file: "content/opptak/index.en.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "bilder"
        label: "Bilder (forside, om oss kor, Eva)"
        file: "data/bilder.yml"
        fields:
          - {label: "Framsidebilde", name: "framsidebilde", widget: "image"}
          - {label: "Bilde av koret", name: "korbilde", widget: "image"}
          - {label: "Bilde av Eva", name: "evabilde", widget: "image"}
      - name: "om-oss"
        label: "Om oss"
        file: "content/om-oss/index.md"
        fields:
          - {label: "Om koret", name: "choir", widget: "markdown"}
          - {label: "Om Eva", name: "eva", widget: "markdown"}
          - {label: "Samarbeidsprosjekter", name: "coops", widget: "markdown"}
      - name: "om-oss-en"
        label: "Om oss (en)"
        file: "content/om-oss/index.en.md"
        fields:
          - {label: "Om koret", name: "choir", widget: "markdown"}
          - {label: "Om Eva", name: "eva", widget: "markdown"}
          - {label: "Samarbeidsprosjekter", name: "coops", widget: "markdown"}
      - name: "album"
        label: "Albumliste"
        file: "data/album.yml"
        fields:
          - label: "Album"
            name: "album"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - {label: "Bilde", name: "img", widget: "image"}
              - {label: "Navn", name: "title", widget: "string"}
              - {label: "Utgitt", name: "date", widget: "datetime", date_format: "MM.YYYY", time_format: false}
              - {label: "Innspillingssted", name: "venue", widget: "string", required: false}
  - name: "prosjekter"
    label: "Prosjekter"
    folder: "content/prosjekter"
    create: true
    i18n: true
    editor:
      preview: false
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "md"
    fields:
      - {label: "Kategori", name: "category", widget: "select", options: ["konsert", "album", "konkurranse"], i18n: duplicate}
      - {label: "Utsolgt", name: "issoldout", widget: "boolean", default: false, required: false, i18n: duplicate}
      - {label: "Få billetter igjen", name: "isfewleft", widget: "boolean", default: false, required: false, i18n: duplicate}
      - {label: "Bilde", name: "eventimg", widget: "image", required: false, i18n: duplicate}
      - {label: "Overskrift", name: "title", widget: "string", i18n: true}
      - {label: "Undertittel", name: "subtitle", widget: "string", required: false, i18n: true}
      - {label: "Tidspunkt", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:ssZZ", i18n: duplicate}
      - {label: "Pris", name: "price", widget: "string", required: false, i18n: duplicate}
      - {label: "Sted", name: "venue", widget: "string", required: false, i18n: true}
      - {label: "Billettlink", name: "ticketlink", widget: "string", required: false, i18n: duplicate}
      - {label: "Beskrivelse", name: "body", widget: "markdown", i18n: true}
      - label: "Omtaler"
        name: "testimonials"
        widget: "list"
        summary: '{{fields.quote}} - {{fields.author}}'
        fields:
           - {label: "Sitat", name: "quote", widget: "string"}
           - {label: "Forfatter", name: "author", widget: "string"}
           - {label: "Kilde", name: "source", widget: "string", required: false}
  - name: "projects"
    editor:
      preview: false
    label: "Projects (en)"
    folder: "content/prosjekter"
    slug: "{{slug}}"
    path: "{{slug}}/index.en"
    extension: "md"
    create: true
    filter: {field: language, value: "en"}
    fields:
      - {label: "Språk", name: "language", widget: "select", options: ["no", "en"], default: "en", required:false}
      - {label: "Kategori", name: "category", widget: "select", options: ["konsert", "album", "konkurranse"]}
      - {label: "Utsolgt", name: "issoldout", widget: "boolean", default: false, required: false}
      - {label: "Få billetter igjen", name: "isfewleft", widget: "boolean", default: false, required: false}
      - {label: "Bilde", name: "eventimg", widget: "image", required: false}
      - {label: "Overskrift", name: "title", widget: "string"}
      - {label: "Undertittel", name: "subtitle", widget: "string", required: false}
      - {label: "Tidspunkt", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Pris", name: "price", widget: "string", required: false}
      - {label: "Sted", name: "venue", widget: "string", required: false}
      - {label: "Billettlink", name: "ticketlink", widget: "string", required: false}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}
      - label: "Omtaler"
        name: "testimonials"
        widget: "list"
        summary: '{{fields.quote}} - {{fields.author}}'
        fields:
           - {label: "Sitat", name: "quote", widget: "string"}
           - {label: "Forfatter", name: "author", widget: "string"}
           - {label: "Kilde", name: "source", widget: "string", required: false}

