backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "sider"
    label: "Sider"
    files:
    - name: "booking"
      label: "Booking"
      file: "content/booking/index.md"
      fields:
        - {label: "Tekst", name: "body", widget: "markdown"}
    - name: "om-oss"
      label: "Om oss"
      file: "content/om-oss/index.md"
      fields:
        - {label: "Om koret", name: "about-choir", widget: "markdown"}
        - {label: "Om Eva", name: "about-Eva", widget: "markdown"}
  - name: "prosjekter"
    label: "Prosjekter"
    folder: "content/prosjekter"
    create: true
    fields:
      - {label: "Kategori", name: "category", widget: "select", options: ["konsert", "album"]}
      - {label: "Overskrift", name: "title", widget: "string"}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}
      - label: "Omtaler"
        name: "testimonials"
        widget: "list"
        summary: '{{fields.quote}} - {{fields.author}}'
        fields:
           - {label: "Sitat", name: "quote", widget: "string"}
           - {label: "Forfatter", name: "author", widget: "string"}





