backend:
  name: git-gateway
  branch: main


media_folder: "static/images"
public_folder: "/images"


collections:
  - name: "sider"
    label: "Sider"
    files:
      - name: "medlemmer"
        label: "Medlemmer"
        file: "data/medlemmer.yml"
        fields:
          - {label: "Sopran", name: "sopran", widget: "text"}
          - {label: "Alt", name: "alt", widget: "text"}
          - {label: "Tenor", name: "tenor", widget: "text"}
          - {label: "Bass", name: "bass", widget: "text"}
      - name: "booking"
        label: "Booking"
        file: "content/booking/index.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "booking_en"
        label: "Booking (en)"
        file: "content/booking/index.en.md"
        fields:
          - {label: "Tittel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - name: "om-oss"
        label: "Om oss"
        file: "content/om-oss/index.md"
        fields:
          - {label: "Om koret", name: "choir", widget: "markdown"}
          - {label: "Om Eva", name: "eva", widget: "markdown"}
          - {label: "Samarbeidsprosjekter", name: "coops", widget: "markdown"}
      - name: "om-oss-en"
        label: "Om oss (en)"
        file: "content/om-oss/index.en.md"
        fields:
          - {label: "Om koret", name: "choir", widget: "markdown"}
          - {label: "Om Eva", name: "eva", widget: "markdown"}
          - {label: "Samarbeidsprosjekter", name: "coops", widget: "markdown"}
  - name: "prosjekter"
    label: "Prosjekter"
    folder: "content/prosjekter"
    slug: "{{slug}}"
    path: "{{slug}}/index.md"
    create: true
    fields:
      - {label: "Kategori", name: "category", widget: "select", options: ["konsert", "album"]}
      - {label: "Bilde", name: "eventimg", widget: "image", required: false}
      - {label: "Overskrift", name: "title", widget: "string"}
      - {label: "Undertittel", name: "subtitle", widget: "string", required: false}
      - {label: "Tidspunkt", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Pris", name: "price", widget: "number", required: false}
      - {label: "Sted", name: "venue", widget: "string", required: false}
      - {label: "Beskrivelse", name: "body", widget: "markdown"}
      - label: "Omtaler"
        name: "testimonials"
        widget: "list"
        summary: '{{fields.quote}} - {{fields.author}}'
        fields:
           - {label: "Sitat", name: "quote", widget: "string"}
           - {label: "Forfatter", name: "author", widget: "string"}
           - {label: "Kilde", name: "source", widget: "string", required: false}

