backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "sider"
    label: "Sider"
    files:
    - name: "booking"
      label: "Booking"
      file: "content/booking/index.md"
      fields:
        - {label: "Tekst", name: "body", widget: "markdown"}
    - name: "om-oss"
      label: "Om oss"
      file: "content/om-oss/index.md"
      fields:
        - {label: "Om koret", name: "about-choir", widget: "markdown"}
        - {label: "Om Eva", name: "about-Eva", widget: "markdown"}




