[[songs]]
title = "Kroppen og rommet"
composer = "Ståle Kleiberg"
text = "Stein Mehren"

[[songs]]
title = "Eg kan ro"
composer = "Fläskkvartetten"
arranger = "Elisabeth Anvik (PUST)"
text = "Freddie Wadling"
solo = "Astrid Grimstad Valheim"

#[[songs]]
#DIE STIMME DES KINDES
#Jaakko Mäntyjärvi
#Tekst: Nikolaus Lenau
#</p>
#  <p class="py-3">
#[[songs]]
#THERE WILL COME SOFT RAINS
# Eriks Ešenvalds
# Tekst: Sara Teasdale
#</p>
#<img src="/program/kroppen-og-rommet/arm.png" class="arm revimg" />
#  <p class="py-3">
#[[songs]]
#ODE TIL KROPPEN
#Heidi Skjerve
#<div class="small">
#ER KROPPEN DITT TEMPEL?Solist: Karen Johanna Kviseth<br />
#
#SLITER DU MED ...?
#
#KVILEPULSSolist: Anne Grete Nyseter<br />
#
#BLOD, SVETTE OG TÅRER<br/>
#
#MIRAKELSolist: Kari Sødal Gjestvang <br />
#
#OVER FJELLSolist: Andreas Tesaker<br />
#
#DIAFRAGMA</div>
#</p>
#  <p class="py-3">
#[[songs]]
#FLJOTAVIK
#PUST, arr: Håvard Gravdal
#Solist: Jon Kristian Bye
#</p>
#<img src="/program/kroppen-og-rommet/arm.png" class="arm" />
#  <p class="py-3">
#[[songs]]
#HA HI HO
#Eva Holm Foosnæs
#</p>
#  <p class="py-3">
#[[songs]]
#DOUBLE DOUBLE TOIL AND TROUBLE
#Jaakko Mäntyjärvi
#Tekst: William Shakespeare (fra Hamlet)
#</p>
#</div>