[no]
title = "Booking"
body = "Kammerkoret Aurum tar på seg oppdrag for organisasjoner og bedrifter, samt private arrangement. Vi utfører oppdrag som fullt kor, eller stiller i mindre grupper om det passer ditt arrangement bedre.\nTa kontakt med oss på post@kammerkoret-aurum.no"

[en]
body = "Kammerkoret Aurum tar på seg oppdrag for organisasjoner og bedrifter, samt private arrangement. Vi utfører oppdrag som fullt kor, eller stiller i mindre grupper om det passer ditt arrangement bedre.\nTa kontakt med oss på post@kammerkoret-aurum.no"
